// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MomAndChildren.Data.Models;

public partial class Brand
{
    public int BrandId { get; set; }

    public string BrandName { get; set; }

    public string Description { get; set; }

    public int Status { get; set; }

    public string Image { get; set; }

    public string Note { get; set; }

    public string CreateBy { get; set; }

    public DateTime CreateAt { get; set; }

    public string UpdateBy { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}