// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MomAndChildren.Data.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public int Status { get; set; }

    public string CreateBy { get; set; }

    public DateTime CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}