// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MomAndChildren.Data.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public string PaymentMethod { get; set; }

    public int Status { get; set; }

    public DateTime PaymentDate { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public string Note { get; set; }

    public string BillingAddress { get; set; }

    public string Currency { get; set; }

    public int OrderId { get; set; }

    public virtual Order Order { get; set; }
}